language: node_js

node_js:
- '6'
- 'stable'

before_install:
- yarn global add codecov
- yarn global add greenkeeper-lockfile@1

before_script:
- greenkeeper-lockfile-update

script:
- yarn run lint
- yarn run test -- --coverage --verbose

after_script:
- codecov
- greenkeeper-lockfile-upload

cache:
  yarn: true
  directories:
  - node_modules
