language: node_js

node_js:
- 6
- stable

before_install:
- yarn global add codecov

script:
- yarn run lint
- yarn run format-check
- yarn run test -- --coverage --verbose

after_script:
- codecov

cache:
  yarn: true
  directories:
  - node_modules
