language: node_js

node_js:
- <%- node_version %>
- stable
<%- write_if_present(
  enable_codecov || enable_greenkeeper,
  '\n' + dedent(`
    before_install:
    ${[
      ...enable_codecov ? ['yarn global add codecov'] : [],
      ...enable_greenkeeper ? ['yarn global add greenkeeper-lockfile@1'] : [],
    ].map(x => `- ${x}`).join('\n')}
  `) + '\n'
) + write_if_present(
  enable_greenkeeper,
  '\n' + dedent(`
    before_script:
    - greenkeeper-lockfile-update
  `) + '\n'
) %>
script:
- yarn run lint
- yarn run test
<%- write_if_present(
  enable_codecov,
  '\n' + dedent(`
    after_script:
    ${[
      ...enable_codecov ? ['codecov'] : [],
      ...enable_greenkeeper ? ['greenkeeper-lockfile-upload'] : [],
    ].map(x => `- ${x}`).join('\n')}
  `) + '\n'
) %>
cache:
  yarn: true
  directories:
  - node_modules

matrix:
  fast_finish: true
