language: node_js

node_js:
<%- node_versions.map(version => `- ${version}`).join('\n') %>

before_install:
- yarn global add codecov

script:
- yarn run lint
- yarn run test -- --coverage --verbose

after_script:
- codecov

cache:
  yarn: true
  directories:
  - node_modules

matrix:
  fast_finish: true
