language: node_js

node_js:
<%- node_versions.map(version => `- ${version}`).join('\n') %>

before_install:
- yarn global add codecov

env:
- JOB=test

script:
- if [ "$JOB" = "lint" ]; then yarn run lint; fi
- if [ "$JOB" = "test" ]; then yarn run test -- --verbose; fi
- if [ "$JOB" = "test-coverage" ]; then yarn run test -- --verbose --coverage; fi

after_script:
- if [ "$JOB" = "test-coverage" ]; then codecov; fi

cache:
  yarn: true
  directories:
  - node_modules

matrix:
  fast_finish: true
  include:
  - node_js: "stable"
    env: JOB=lint
  - node_js: "stable"
    env: JOB=test-coverage
