language: node_js

node_js:
<%- node_versions.map(version => `- ${version}`).join('\n') %>
<%- write_if_present(
  enable_codecov,
  '\n' + dedent(`
    before_install:
    - yarn global add codecov
  `) + '\n'
) %>
script:
- yarn run lint
- yarn run test -- --coverage --verbose
<%- write_if_present(
  enable_codecov,
  '\n' + dedent(`
    after_script:
    - codecov
  `) + '\n'
) %>
cache:
  yarn: true
  directories:
  - node_modules

matrix:
  fast_finish: true
